import os
import sys
currentdir = os.path.dirname(os.path.realpath(__file__))
parentdir = os.path.dirname(currentdir)
parentdir = os.path.dirname(parentdir)

sys.path.append(parentdir)
import engine as e
from built_in import built_in_funcs,built_in_preds


"Test per verificare il funzionamento dei simboli di funzione"
en = e.Engine(built_in_funcs,built_in_preds)
en.load_kb('f_sym')
f = e.parse('p(sum(succ(succ(succ(9))),3)).')
print('query: '+str(f[0]))
ans = en.prove(f)
print(ans)
print()
f = e.parse('p(mul(succ(succ(succ(9))),3)).')
print('query: '+str(f[0]))
ans = en.prove(f)
print(ans)
print()
f = e.parse('p(div(succ(succ(succ(9))),3)).')
print('query: '+str(f[0]))
ans = en.prove(f)
print(ans)
print()
f = e.parse('p(sub(succ(succ(succ(9))),3)).')
print('query: '+str(f[0]))
ans = en.prove(f)
print(ans)
print()
f = e.parse('greater(sum(succ(succ(succ(9))),3),14).')
print('query: '+str(f[0]))
ans = en.prove(f)
print(ans)
print()
f = e.parse('greater_equal(sum(succ(succ(succ(9))),3),sum(succ(succ(succ(9))),3)).')
print('query: '+str(f[0]))
ans = en.prove(f)
print(ans)
print()
f = e.parse('p(f(x)).')
print('query: '+str(f[0]))
ans = en.prove(f)
print(ans)
